spring.application.name=ProjetLTW
### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/ltwdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

### JPA / HIBERNATE ###
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
server.port=8081

### Loging / SLF4J ###
logging.level.com.example.projetltw=DEBUG
logging.file.name=logs/ProjetLTW.log